# Generated by Django 3.1.3 on 2021-02-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='death_date',
            field=models.DateField(),
        ),
    ]
