# Generated by Django 3.1.3 on 2021-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210207_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
