# Generated by Django 3.1.7 on 2021-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210207_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
