# Generated by Django 3.1.7 on 2021-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210321_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_types',
            field=models.CharField(blank=True, choices=[('Work', 'WORK'), ('Home', 'HOME'), ('Other', 'OTHER'), ('none', 'NONE')], default='none', help_text='type', max_length=5),
        ),
    ]
