# Generated by Django 3.1.7 on 2022-01-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth_day',
            field=models.CharField(default='DD', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='birth_month',
            field=models.CharField(default='MM', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='birth_year',
            field=models.CharField(default='YY', max_length=4),
        ),
        migrations.AddField(
            model_name='contact',
            name='death_day',
            field=models.CharField(default='DD', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='death_month',
            field=models.CharField(default='MM', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='death_year',
            field=models.CharField(default='YY', max_length=4),
        ),
    ]
