# Generated by Django 3.1.7 on 2022-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20220110_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='First Name', max_length=200),
        ),
    ]
