# Generated by Django 3.1.7 on 2022-01-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20220110_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, default='Company', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, default='Job Title', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(default='Middle Name', max_length=200),
        ),
    ]
