# Generated by Django 3.1.7 on 2022-01-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20220110_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_types',
            field=models.CharField(blank=True, choices=[('Work', 'WORK'), ('Home', 'HOME'), ('Other', 'OTHER')], default='none', max_length=5),
        ),
    ]
