# Generated by Django 3.1.7 on 2022-01-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20220114_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_day',
            field=models.CharField(default='DD', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birth_month',
            field=models.CharField(default='MM', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='death_day',
            field=models.CharField(default='DD', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='death_month',
            field=models.CharField(default='MM', max_length=2),
        ),
    ]
