# Generated by Django 3.1.7 on 2022-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20220116_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='city', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='state', max_length=5, null=True)),
                ('zip_code', models.CharField(blank=True, default='zip', max_length=10, null=True)),
            ],
        ),
    ]
