# Generated by Django 3.1.7 on 2022-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='city', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, default='state', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(blank=True, default='zip', max_length=10, null=True),
        ),
    ]
