# Generated by Django 3.1.7 on 2022-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20220119_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
    ]
