# Generated by Django 3.1.7 on 2022-01-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_contact_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_test',
            name='city',
            field=models.CharField(default='city', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact_test',
            name='state',
            field=models.CharField(blank=True, default='state', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact_test',
            name='zip_code',
            field=models.CharField(blank=True, default='zip', max_length=500, null=True),
        ),
    ]
