# Generated by Django 3.1.3 on 2021-01-06 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('artist_email', models.EmailField(max_length=200)),
                ('artist_phone', models.CharField(help_text="Enter phone number in format 'xxx-xxx-xxxx", max_length=12)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('piece_upload', models.ImageField(upload_to='images/')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pieces.artist')),
            ],
            options={
                'ordering': ['title', 'artist'],
            },
        ),
        migrations.CreateModel(
            name='PieceInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this piece instance', primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Add Description', max_length=500)),
                ('medium', models.CharField(max_length=200)),
                ('subject_matter', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_of_upload', models.DateField(blank=True, null=True)),
                ('types', models.CharField(blank=True, choices=[('painting', 'PAINTING'), ('sculpture', 'SCULPTURE'), ('textile', 'TEXTTILE'), ('photograph', 'PHOTOGRAPH'), ('none', 'NONE')], default='none', help_text='type', max_length=10)),
                ('visibility', models.CharField(blank=True, choices=[('Private', 'PRIVATE'), ('Public', 'PUBLIC')], default='none', help_text='type', max_length=10)),
                ('availability', models.CharField(blank=True, choices=[('Unfinished', 'UNFINISHED'), ('Complete', 'COMPLETE'), ('Pending', 'PENDING'), ('Sold', 'SOLD')], default='none', help_text='type', max_length=10)),
                ('dim', models.CharField(blank=True, choices=[('inches', 'INCHES'), ('centimeters', 'CENTIMETERS')], default='none', help_text='type', max_length=15)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pieces.piece')),
            ],
            options={
                'ordering': ['date_of_upload'],
            },
        ),
    ]
