# Generated by Django 3.1.3 on 2021-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_auto_20210106_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceinstance',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
