# Generated by Django 3.1.3 on 2021-01-27 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0006_auto_20210106_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPiece_1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this piece instance', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('comment', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
    ]
