# Generated by Django 3.1.3 on 2021-02-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0008_pieceonly_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('photo_compressed', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
