# Generated by Django 3.1.3 on 2021-02-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
