# Generated by Django 3.1.3 on 2021-02-18 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pieces', '0012_auto_20210217_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendship_creator_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
