# Generated by Django 3.1.3 on 2021-02-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pieces', '0021_auto_20210219_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpiece',
            name='uploader',
        ),
        migrations.AddField(
            model_name='newpiece',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
