# Generated by Django 3.1.3 on 2021-02-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0030_auto_20210222_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpiece',
            name='uploader',
        ),
    ]
