# Generated by Django 3.1.3 on 2021-03-02 06:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0031_remove_newpiece_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpiece',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
    ]
