# Generated by Django 3.1.3 on 2021-03-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0033_auto_20210304_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpiece',
            name='tags',
        ),
    ]
