# Generated by Django 3.1.3 on 2021-03-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0036_auto_20210304_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidtaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.tag'),
        ),
    ]
