# Generated by Django 3.1.7 on 2021-03-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0039_auto_20210320_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pieces.artist'),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='depth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='description',
            field=models.TextField(blank=True, help_text='Add Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='subject_matter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
