# Generated by Django 3.1.7 on 2021-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0040_auto_20210320_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='availability',
            field=models.CharField(blank=True, choices=[('Unfinished', 'UNFINISHED'), ('Complete', 'COMPLETE'), ('Pending', 'PENDING'), ('Sold', 'SOLD')], help_text='type', max_length=10),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='dim',
            field=models.CharField(blank=True, choices=[('inches', 'INCHES'), ('centimeters', 'CENTIMETERS')], help_text='type', max_length=15),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='types',
            field=models.CharField(blank=True, choices=[('painting', 'PAINTING'), ('sculpture', 'SCULPTURE'), ('textile', 'TEXTTILE'), ('photograph', 'PHOTOGRAPH'), ('none', 'NONE')], help_text='type', max_length=10),
        ),
    ]
