# Generated by Django 3.1.7 on 2021-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0043_auto_20210702_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicOnly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
