# Generated by Django 3.1.7 on 2021-07-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0045_auto_20210730_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piconly',
            old_name='upload',
            new_name='upload_pic',
        ),
    ]
