# Generated by Django 3.1.7 on 2021-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0046_auto_20210730_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='types',
            field=models.CharField(blank=True, choices=[('painting', 'PAINTING'), ('sculpture', 'SCULPTURE'), ('textile', 'TEXTTILE'), ('photograph', 'PHOTOGRAPH'), ('none', 'NONE')], max_length=10),
        ),
    ]
