# Generated by Django 3.1.7 on 2021-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0047_auto_20210811_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='availability',
            field=models.CharField(blank=True, choices=[('Unfinished', 'UNFINISHED'), ('Complete', 'COMPLETE'), ('Pending', 'PENDING'), ('Sold', 'SOLD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='dim',
            field=models.CharField(blank=True, choices=[('inches', 'INCHES'), ('centimeters', 'CENTIMETERS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Private', 'PRIVATE'), ('Public', 'PUBLIC')], max_length=10),
        ),
    ]
