# Generated by Django 3.1.7 on 2021-08-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0049_auto_20210811_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
