# Generated by Django 3.1.7 on 2021-08-11 19:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pieces', '0050_auto_20210811_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pieces.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
