# Generated by Django 3.1.7 on 2021-08-23 04:06

from django.db import migrations, models
import django.db.models.deletion
import pieces.models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0052_auto_20210818_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pieces.models.upload_gallery_image)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pieces.pet')),
            ],
        ),
    ]
