# Generated by Django 3.1.7 on 2021-09-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0055_auto_20210901_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='types',
            field=models.CharField(choices=[('Add Type', 'ADD TYPE'), ('painting', 'PAINTING'), ('sculpture', 'SCULPTURE'), ('textile', 'TEXTTILE'), ('photograph', 'PHOTOGRAPH'), ('none', 'NONE')], default='UNFINISHED', max_length=10),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='visibility',
            field=models.CharField(choices=[('Private', 'PRIVATE'), ('Public', 'PUBLIC')], default='PRIVATE', max_length=10),
        ),
    ]
