# Generated by Django 3.1.7 on 2021-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0056_auto_20210901_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='availability',
            field=models.CharField(choices=[('Unfinished', 'UNFINISHED'), ('Complete', 'COMPLETE'), ('Pending', 'PENDING'), ('Sold', 'SOLD')], default='Unfinished', max_length=10),
        ),
    ]
