# Generated by Django 3.1.7 on 2021-09-25 04:26

from django.db import migrations, models
import django.db.models.deletion
import pieces.models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0057_auto_20210901_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PieceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pieces.models.upload_piece_image)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pieces.uploadpiece')),
            ],
        ),
    ]
