# Generated by Django 3.1.7 on 2021-10-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0058_pieceimage_uploadpiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
