# Generated by Django 3.1.7 on 2021-10-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0059_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='upload_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
