# Generated by Django 3.1.7 on 2021-10-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0061_auto_20211020_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='upload_pic',
            field=models.ImageField(blank=True, upload_to='GeeksModels/images/'),
        ),
    ]
