# Generated by Django 3.1.7 on 2021-10-28 05:34

from django.db import migrations, models
import django.db.models.deletion
import pieces.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pieces', '0062_auto_20211020_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPiece2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this piece instance', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('medium', models.CharField(blank=True, max_length=200)),
                ('subject_matter', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('depth', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('date_of_upload', models.DateField(blank=True, null=True)),
                ('types', models.CharField(choices=[('Add Type', 'ADD TYPE'), ('painting', 'PAINTING'), ('sculpture', 'SCULPTURE'), ('textile', 'TEXTTILE'), ('photograph', 'PHOTOGRAPH'), ('none', 'NONE')], default='UNFINISHED', max_length=10)),
                ('dim', models.CharField(blank=True, choices=[('inches', 'INCHES'), ('centimeters', 'CENTIMETERS')], max_length=15)),
                ('visibility', models.CharField(choices=[('Private', 'PRIVATE'), ('Public', 'PUBLIC')], default='PRIVATE', max_length=10)),
                ('availability', models.CharField(choices=[('Unfinished', 'UNFINISHED'), ('Complete', 'COMPLETE'), ('Pending', 'PENDING'), ('Sold', 'SOLD')], default='Unfinished', max_length=10)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pieces.artist')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pieces.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PieceImage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pieces.models.upload_piece_image)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pieces.newpiece2')),
            ],
        ),
    ]
