# Generated by Django 3.1.7 on 2021-12-27 19:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('pieces', '0064_auto_20211227_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add Tags', through='pieces.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
