# Generated by Django 3.1.7 on 2021-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0066_auto_20211227_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpiece',
            name='edition_num',
            field=models.IntegerField(default=0),
        ),
    ]
