# Generated by Django 3.1.7 on 2021-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0067_newpiece_edition_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpiece',
            name='edition_dom',
            field=models.IntegerField(default=0),
        ),
    ]
