# Generated by Django 3.1.7 on 2021-12-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0069_auto_20211227_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpiece',
            name='day',
            field=models.IntegerField(default=28, max_length=2),
        ),
        migrations.AddField(
            model_name='newpiece',
            name='month',
            field=models.IntegerField(default=12, max_length=2),
        ),
        migrations.AddField(
            model_name='newpiece',
            name='year',
            field=models.IntegerField(default=2021, max_length=4),
        ),
    ]
