# Generated by Django 3.1.7 on 2021-12-28 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0070_auto_20211228_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
