# Generated by Django 3.1.7 on 2021-12-28 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0071_auto_20211228_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='day',
            field=models.IntegerField(default=28, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='month',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
