# Generated by Django 3.1.7 on 2021-12-28 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0072_auto_20211228_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='year',
            field=models.IntegerField(default='YY', validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
