# Generated by Django 3.1.7 on 2021-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0073_auto_20211228_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='day',
            field=models.CharField(default='DD', max_length=2),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='month',
            field=models.CharField(default='MM', max_length=2),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='year',
            field=models.CharField(default='YY', max_length=4),
        ),
    ]
