# Generated by Django 3.1.7 on 2021-12-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0075_auto_20211228_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='year',
            field=models.CharField(default='YY', max_length=4),
        ),
    ]
