# Generated by Django 3.1.7 on 2021-12-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0076_auto_20211228_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='depth',
            field=models.CharField(default='D', max_length=3),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='height',
            field=models.CharField(default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='width',
            field=models.CharField(default='W', max_length=3),
        ),
    ]
