# Generated by Django 3.1.7 on 2021-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0077_auto_20211228_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='edition_dom',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='edition_num',
            field=models.CharField(default='00', max_length=3),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='price',
            field=models.CharField(default='Add Price', max_length=10),
        ),
    ]
