# Generated by Django 3.1.7 on 2021-12-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0078_auto_20211228_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpiece',
            name='edition_dom',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='newpiece',
            name='edition_num',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
