# Generated by Django 3.1.3 on 2021-01-06 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['artist']},
        ),
        migrations.AlterModelOptions(
            name='pieceinstance',
            options={'ordering': ['date_of_upload', 'availability']},
        ),
        migrations.RemoveField(
            model_name='piece',
            name='title',
        ),
        migrations.AddField(
            model_name='pieceinstance',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
