# Generated by Django 3.1.3 on 2021-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_newpiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceinstance',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pieceinstance',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pieceinstance',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pieceinstance',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
