# Generated by Django 3.1.3 on 2021-01-10 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique uuid for contact', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=200)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('death_date', models.DateField(auto_now_add=True)),
                ('bio', models.TextField(max_length=1000)),
                ('notes', models.TextField(max_length=1000)),
                ('contact_types', models.CharField(blank=True, choices=[('Work', 'WORK'), ('Home', 'HOME'), ('Other', 'OTHER')], default='none', help_text='type', max_length=5)),
                ('contact_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
